# docker-compose.yml

version: "3"

services:
  elfa-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ELFA_API_KEY=${ELFA_API_KEY}
    volumes:
      - ./config:/app/config
    # Standard input/output need to be handled specially for MCP
    stdin_open: true
    tty: true
