# .github/workflows/python-tests.yaml
name: Python Tests

on:
  workflow_dispatch:  # Enables manual trigger
  push:
    paths:
      - "python/**"
  pull_request:
    paths:
      - "python/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install hatchling
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install -e .

      - name: Run tests
        run: |
          pytest tests/ --cov=elfa_mcp --cov-report=xml

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./python/coverage.xml
          flags: python
